"""Dependency-free tabular and SVG reporting."""

from __future__ import annotations

from collections import defaultdict
from html import escape
from pathlib import Path
from statistics import mean
from typing import Any, Iterable, Mapping, Sequence
import csv


def write_csv(
    path: str | Path, rows: Iterable[Mapping[str, Any]], fieldnames: Sequence[str] | None = None
) -> Path:
    material = tuple(rows)
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    if fieldnames is None:
        fieldnames = tuple(
            sorted({key for row in material for key in row})
        )
    with destination.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(material)
    return destination


def grouped_mean(
    rows: Iterable[Mapping[str, Any]], *, by: Sequence[str], metric: str
) -> tuple[dict[str, Any], ...]:
    groups: dict[tuple[Any, ...], list[float]] = defaultdict(list)
    for row in rows:
        value = row.get(metric)
        if value is None:
            continue
        groups[tuple(row[key] for key in by)].append(float(value))
    output = []
    for key, values in sorted(groups.items(), key=lambda pair: repr(pair[0])):
        output.append(
            {
                **dict(zip(by, key)),
                metric: mean(values),
                "n": len(values),
            }
        )
    return tuple(output)


def write_line_svg(
    path: str | Path,
    series: Mapping[str, Sequence[tuple[float, float]]],
    *,
    title: str,
    x_label: str,
    y_label: str,
    width: int = 900,
    height: int = 520,
) -> Path:
    """Write a compact accessible SVG without a plotting dependency."""

    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    points = [point for values in series.values() for point in values]
    if not points:
        raise ValueError("cannot plot an empty series")
    xs, ys = [point[0] for point in points], [point[1] for point in points]
    x_min, x_max = min(xs), max(xs)
    y_min, y_max = min(ys), max(ys)
    if x_min == x_max:
        x_min, x_max = x_min - 0.5, x_max + 0.5
    if y_min == y_max:
        y_min, y_max = y_min - 0.5, y_max + 0.5
    left, right, top, bottom = 90, 30, 60, 75
    plot_w, plot_h = width - left - right, height - top - bottom

    def project(point: tuple[float, float]) -> tuple[float, float]:
        x, y = point
        px = left + (x - x_min) / (x_max - x_min) * plot_w
        py = top + (y_max - y) / (y_max - y_min) * plot_h
        return px, py

    palette = ("#2563eb", "#dc2626", "#059669", "#7c3aed", "#d97706", "#0891b2")
    body = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" role="img" aria-labelledby="title desc">',
        f'<title id="title">{escape(title)}</title>',
        '<desc id="desc">Line chart generated by CAPE-Loop.</desc>',
        '<rect width="100%" height="100%" fill="white"/>',
        f'<text x="{width/2}" y="30" text-anchor="middle" font-size="20" '
        f'font-family="sans-serif">{escape(title)}</text>',
        f'<line x1="{left}" y1="{top + plot_h}" x2="{left + plot_w}" '
        f'y2="{top + plot_h}" stroke="#111827"/>',
        f'<line x1="{left}" y1="{top}" x2="{left}" y2="{top + plot_h}" '
        f'stroke="#111827"/>',
        f'<text x="{left + plot_w/2}" y="{height - 20}" text-anchor="middle" '
        f'font-family="sans-serif">{escape(x_label)}</text>',
        f'<text x="20" y="{top + plot_h/2}" text-anchor="middle" '
        f'transform="rotate(-90 20 {top + plot_h/2})" font-family="sans-serif">'
        f'{escape(y_label)}</text>',
    ]
    for index, (label, values) in enumerate(sorted(series.items())):
        color = palette[index % len(palette)]
        projected = [project(point) for point in sorted(values)]
        path_data = " ".join(
            ("M" if point_index == 0 else "L") + f" {x:.2f} {y:.2f}"
            for point_index, (x, y) in enumerate(projected)
        )
        body.append(
            f'<path d="{path_data}" fill="none" stroke="{color}" stroke-width="2"/>'
        )
        for x, y in projected:
            body.append(f'<circle cx="{x:.2f}" cy="{y:.2f}" r="3" fill="{color}"/>')
        legend_y = top + index * 22
        body.append(
            f'<rect x="{left + plot_w - 145}" y="{legend_y - 10}" width="14" '
            f'height="3" fill="{color}"/><text x="{left + plot_w - 125}" '
            f'y="{legend_y - 5}" font-size="12" font-family="sans-serif">'
            f'{escape(label)}</text>'
        )
    body.append("</svg>")
    destination.write_text("\n".join(body) + "\n", encoding="utf-8")
    return destination

